<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_58d2bc85052c4',
	'title' => 'Contact form options',
	'fields' => array (
		array (
			'key' => 'field_58d2bc850b199',
			'label' => 'Form Shortcode',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Copy and paste the following Shortcode where you want the contact form.

<strong>[perf_contact_form]</strong>',
			'esc_html' => 0,
			'new_lines' => 'wpautop',
		),
		array (
			'key' => 'field_58d2bc850b234',
			'label' => 'Success message',
			'name' => 'perf_contact_success_message',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58d2bc850b298',
			'label' => 'Error message',
			'name' => 'perf_contact_error_message',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'br',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58d2bc850b332',
			'label' => 'Notification email',
			'name' => 'perf_contact_notification_email',
			'type' => 'email',
			'instructions' => 'Default: WordPress admin',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58d2bc850b3e8',
			'label' => 'Google reCAPTCHA?',
			'name' => 'perf_contact_recaptcha',
			'type' => 'true_false',
			'instructions' => 'If you get spam submission, activate that option.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => 'Activated',
			'ui_off_text' => 'Disabled',
		),
		array (
			'key' => 'field_58d2bc850b44d',
			'label' => 'Google reCAPTCHA public key',
			'name' => 'perf_contact_public_key',
			'type' => 'text',
			'instructions' => 'Get your public key here: <a href="https://www.google.com/recaptcha/intro/index.html" target="_blank">https://www.google.com/recaptcha/intro/index.html</a>',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58d2bc850b3e8',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_58d2bc850b4e7',
			'label' => 'Google reCAPTCHA secret key',
			'name' => 'perf_contact_private_key_copy',
			'type' => 'text',
			'instructions' => 'Get your private key here: <a href="https://www.google.com/recaptcha/intro/index.html" target="_blank">https://www.google.com/recaptcha/intro/index.html</a>',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_58d2bc850b3e8',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-contact-form',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'menu_item_level' => 'all',
));

endif;